name: system_screenshot
description: Take a native screenshot from the system interface
version: 0.0.1
homepage: https://github.com/SwissCheese5/system_screenshot/
repository: https://github.com/SwissCheese5/system_screenshot/

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: SystemScreenshotPlugin